### ISSUE TITLE
Error when encoding BSC USDC to BNB

### ISSUE THREAD

**Issue by xykota** [sifiorg/sifi#410]
![image](https://github.com/sifiorg/sifi/assets/128569957/e998a393-fbd5-49aa-a82a-03c5cc864406)

**Comment by ALIR86** [comment]
This isnot my wallet still hasnot wallet metamask you haven't I wanna new install to hope GOD  with help and a upport  guthub.com  to fix bugs about extension  browser no provider in chrome now why donot install in browser edge

**Comment by xykota** [comment]
> This isnot my wallet still hasnot wallet metamask you haven't I wanna new install to hope GOD with help and a upport guthub.com to fix bugs about extension browser no provider in chrome now why donot install in browser edge

Can you clarify?

**Comment by xykota** [comment]
Cannot reproduce without knowing the quote
