### ISSUE TITLE
Can't receive partner tokens

### ISSUE THREAD

**Issue by boriskubrik** [sifiorg/sifi#416]
I'm struggling to generate partner token balances after succesful swaps. I've tried on several chains.  Wallet: `0x1b43cBa142D18beD5FE3DB91DA04e1A90FCcdfcE`

My payload, referring the same wallet:

![image](https://github.com/sifiorg/sifi/assets/128667801/2d04edfc-bad3-4d98-b8d2-ae0f03a4f457)

TX: https://optimistic.etherscan.io/tx/0x15b47a6be0fe933720b9557ecf2b95913a532da79f46f455210861ebb272722c

Subgraph:
https://api.thegraph.com/subgraphs/name/sifiorg/sifi-optimism/graphql?query=+query+GetPartnerTokens%28%24id%3A+ID%21%29+%7B%0A++++partner%28id%3A+%24id%29+%7B%0A++++++id%0A++++++tokens+%7B%0A++++++++id%0A++++++++balance%0A++++++++balanceDecimal%0A++++++++balanceUsd%0A++++++++withdrawn%0A++++++++withdrawnDecimal%0A++++++++withdrawnUsd%0A++++++++modifiedAt%0A++++++++modifiedAtBlock%0A++++++++modifiedAtTransaction%0A++++++%7D%0A++++%7D%0A++%7D

![image](https://github.com/sifiorg/sifi/assets/128667801/96bcef03-6bce-4760-bf4e-ecb6d7b80a17)

What am I missing? @xykota

**Comment by xykota** [comment]
> I'm struggling to generate partner token balances after succesful swaps. I've tried on several chains. Wallet: `0x1b43cBa142D18beD5FE3DB91DA04e1A90FCcdfcE`
> 
> My payload, referring the same wallet:
> 
> ![image](https://user-images.githubusercontent.com/128667801/281539683-2d04edfc-bad3-4d98-b8d2-ae0f03a4f457.png)
> 
> TX: [optimistic.etherscan.io/tx/0x15b47a6be0fe933720b9557ecf2b95913a532da79f46f455210861ebb272722c](https://optimistic.etherscan.io/tx/0x15b47a6be0fe933720b9557ecf2b95913a532da79f46f455210861ebb272722c)
> 
> Subgraph: [api.thegraph.com/subgraphs/name/sifiorg/sifi-optimism/graphql?query=+query+GetPartnerTokens%28%24id%3A+ID%21%29+%7B%0A++++partner%28id%3A+%24id%29+%7B%0A++++++id%0A++++++tokens+%7B%0A++++++++id%0A++++++++balance%0A++++++++balanceDecimal%0A++++++++balanceUsd%0A++++++++withdrawn%0A++++++++withdrawnDecimal%0A++++++++withdrawnUsd%0A++++++++modifiedAt%0A++++++++modifiedAtBlock%0A++++++++modifiedAtTransaction%0A++++++%7D%0A++++%7D%0A++%7D](https://api.thegraph.com/subgraphs/name/sifiorg/sifi-optimism/graphql?query=+query+GetPartnerTokens%28%24id%3A+ID%21%29+%7B%0A++++partner%28id%3A+%24id%29+%7B%0A++++++id%0A++++++tokens+%7B%0A++++++++id%0A++++++++balance%0A++++++++balanceDecimal%0A++++++++balanceUsd%0A++++++++withdrawn%0A++++++++withdrawnDecimal%0A++++++++withdrawnUsd%0A++++++++modifiedAt%0A++++++++modifiedAtBlock%0A++++++++modifiedAtTransaction%0A++++++%7D%0A++++%7D%0A++%7D)
> 
> ![image](https://user-images.githubusercontent.com/128667801/281539985-96bcef03-6bce-4760-bf4e-ecb6d7b80a17.png)
> 
> What am I missing? @xykota

It's case sensitive, use the lowercase `0x1b43cba142d18bed5fe3db91da04e1a90fccdfce` as the ID. Everything else is correct.
