### ISSUE TITLE
Quote shown as zero before allowance set

### ISSUE THREAD

**Issue by xykota** [sifiorg/sifi#444]
<img width="499" alt="image" src="https://github.com/sifiorg/sifi/assets/128569957/83fb78d8-3c38-4ef9-a727-7113092ddb6f">

**Comment by xykota** [comment]
<img width="510" alt="image" src="https://github.com/sifiorg/sifi/assets/128569957/aef6f2ef-0f01-4c84-b73f-38c570d65e2b">

**Comment by boriskubrik** [comment]
Duplicate of #415
