### ISSUE TITLE
regional redirect contains minor typo

### ISSUE THREAD

**Issue by c3w7** [sifiorg/sifi#451]
Redirect banner contains "SIRI" instead of "SIFI"

![Screenshot_2023-11-23-06-43-46-62_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/sifiorg/sifi/assets/148763836/281d57b0-e157-498d-8885-0954be75106e)

**Comment by boriskubrik** [comment]
Fix is scheduled.
